(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-shop/app-shop"],{"400c":function(t,n,e){"use strict";e.r(n);var u=e("e21a"),a=e("dad3");for(var o in a)"default"!==o&&function(t){e.d(n,t,function(){return a[t]})}(o);e("7226");var r=e("2877"),i=Object(r["a"])(a["default"],u["a"],u["b"],!1,null,"d50e63f8",null);n["default"]=i.exports},7226:function(t,n,e){"use strict";var u=e("a06a"),a=e.n(u);a.a},"9abd":function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var u={name:"app-shop",props:{list:{type:Array,default:function(){return[]}},navPicUrl:{type:String,default:function(){return""}},scorePicUrl:{type:String,default:function(){return""}},showName:{type:Boolean,default:function(){return!0}},showScore:{type:Boolean,default:function(){return!0}},showTel:{type:Boolean,default:function(){return!0}},scrollTop:{type:Number,default:function(){return 0}},value:{type:Boolean,default:function(){return!0}}},data:function(){return{height:0,request:!0}},created:function(){var t=this;wx.getSystemInfo({success:function(n){t.height=n.windowHeight}})},methods:{autoEnd:function(){var t=this;this.$lazyLoadingData("app-shop").then(function(n){n[0].height+n[0].top<t.height&&(t.request=!1,t.$emit("input",t.request))})}},watch:{scrollTop:{handler:function(t,n){t>n&&this.request&&this.autoEnd()}}}};n.default=u},a06a:function(t,n,e){},dad3:function(t,n,e){"use strict";e.r(n);var u=e("9abd"),a=e.n(u);for(var o in u)"default"!==o&&function(t){e.d(n,t,function(){return u[t]})}(o);n["default"]=a.a},e21a:function(t,n,e){"use strict";var u=function(){var t=this,n=t.$createElement;t._self._c},a=[];e.d(n,"a",function(){return u}),e.d(n,"b",function(){return a})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-shop/app-shop-create-component',
    {
        'components/page-component/app-shop/app-shop-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("400c"))
        })
    },
    [['components/page-component/app-shop/app-shop-create-component']]
]);                
