(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/basic-component/app-rich/components/wxParseTemplate0"],{"2a8a":function(n,e,t){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o=function(){return t.e("components/basic-component/app-rich/components/wxParseTemplate1").then(t.bind(null,"1c24"))},a=function(){return Promise.all([t.e("common/vendor"),t.e("components/basic-component/app-rich/components/wxParseImg")]).then(t.bind(null,"50a5"))},r=function(){return t.e("components/basic-component/app-rich/components/wxParseVideo").then(t.bind(null,"b9a8d"))},c=function(){return t.e("components/basic-component/app-rich/components/wxParseAudio").then(t.bind(null,"d2fa"))},i=function(){return t.e("components/basic-component/app-rich/components/wxParseTable").then(t.bind(null,"7194"))},u={name:"wxParseTemplate0",props:{node:{type:Object,default:function(){return{}}}},components:{wxParseTemplate:o,wxParseImg:a,wxParseVideo:r,wxParseAudio:c,wxParseTable:i},methods:{wxParseATap:function(n,e){var t=e.currentTarget.dataset.href;if(t){var o=this.$parent;while(!o.preview||"function"!==typeof o.preview)o=o.$parent;o.navigate(t,e,n)}}}};e.default=u},8085:function(n,e,t){"use strict";t.r(e);var o=t("bca0"),a=t("f75e");for(var r in a)"default"!==r&&function(n){t.d(e,n,function(){return a[n]})}(r);var c=t("2877"),i=Object(c["a"])(a["default"],o["a"],o["b"],!1,null,null,null);e["default"]=i.exports},bca0:function(n,e,t){"use strict";var o=function(){var n=this,e=n.$createElement;n._self._c},a=[];t.d(e,"a",function(){return o}),t.d(e,"b",function(){return a})},f75e:function(n,e,t){"use strict";t.r(e);var o=t("2a8a"),a=t.n(o);for(var r in o)"default"!==r&&function(n){t.d(e,n,function(){return o[n]})}(r);e["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/basic-component/app-rich/components/wxParseTemplate0-create-component',
    {
        'components/basic-component/app-rich/components/wxParseTemplate0-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("8085"))
        })
    },
    [['components/basic-component/app-rich/components/wxParseTemplate0-create-component']]
]);                
