(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["plugins/region/components/app-index/app-index"],{7480:function(t,e,n){},bd45:function(t,e,n){"use strict";n.r(e);var r=n("bfda"),i=n("f443");for(var o in i)"default"!==o&&function(t){n.d(e,t,function(){return i[t]})}(o);n("f42d2");var a=n("2877"),u=Object(a["a"])(i["default"],r["a"],r["b"],!1,null,"2e94f8e9",null);e["default"]=u.exports},bfda:function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return i})},c99e:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function i(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function o(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?i(n,!0).forEach(function(e){a(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):i(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function a(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var u={name:"app-index",props:{detail:{type:Object},setting:{type:Object}},computed:o({},(0,r.mapState)({region:function(t){return t.mallConfig.__wxapp_img.region}})),methods:{toUpdate:function(){1==this.detail.is_up&&this.detail.level_up_log&&2==this.detail.level_up_log.status?t.navigateTo({url:"/plugins/region/index/index?up=1"}):t.navigateTo({url:"/plugins/region/update/update"})},toCash:function(){t.navigateTo({url:"/plugins/region/cash/cash"})},toBonus:function(){var e=this.setting.form.region?this.setting.form.region:"",n=this.setting.form.cash_detail?this.setting.form.cash_detail:"";t.navigateTo({url:"/plugins/region/bonus/bonus?name="+e+"&cash_detail="+n})},toDetail:function(){var e=this.setting.form.cash_detail?this.setting.form.cash_detail:"";t.navigateTo({url:"/plugins/region/cash-detail/cash-detail?name="+e})},toOrder:function(){var e=this.setting.form.order?this.setting.form.order:"";t.navigateTo({url:"/plugins/region/order/order?name="+e})},toAbout:function(){t.navigateTo({url:"/plugins/region/about/about"})}},creatd:function(t){}};e.default=u}).call(this,n("543d")["default"])},f42d2:function(t,e,n){"use strict";var r=n("7480"),i=n.n(r);i.a},f443:function(t,e,n){"use strict";n.r(e);var r=n("c99e"),i=n.n(r);for(var o in r)"default"!==o&&function(t){n.d(e,t,function(){return r[t]})}(o);e["default"]=i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'plugins/region/components/app-index/app-index-create-component',
    {
        'plugins/region/components/app-index/app-index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("bd45"))
        })
    },
    [['plugins/region/components/app-index/app-index-create-component']]
]);                
