(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["plugins/bargain/common-buttom"],{"22e0":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=e("2f62");function r(t,n){var e=Object.keys(t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(t);n&&(o=o.filter(function(n){return Object.getOwnPropertyDescriptor(t,n).enumerable})),e.push.apply(e,o)}return e}function i(t){for(var n=1;n<arguments.length;n++){var e=null!=arguments[n]?arguments[n]:{};n%2?r(e,!0).forEach(function(n){u(t,n,e[n])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(e)):r(e).forEach(function(n){Object.defineProperty(t,n,Object.getOwnPropertyDescriptor(e,n))})}return t}function u(t,n,e){return n in t?Object.defineProperty(t,n,{value:e,enumerable:!0,configurable:!0,writable:!0}):t[n]=e,t}var a=function(){return e.e("components/page-component/app-iphonex-bottom/app-iphonex-bottom").then(e.bind(null,"bc3b"))},c=function(){return e.e("components/basic-component/app-iphone-x/app-iphone-x").then(e.bind(null,"7598"))},p=function(){return e.e("components/basic-component/app-empty-bottom/app-empty-bottom").then(e.bind(null,"0c06"))},f={name:"common-buttom",components:{appIphonexBottom:a,appEmptyBottom:p,appIphoneX:c},computed:i({},(0,o.mapState)("gConfig",{iphone:function(t){return t.iphone},iphoneHeight:function(t){return t.iphoneHeight}})),props:{status:{type:String,default:"index"},theme:String},data:function(){return{}},methods:{nav1:function(){t.redirectTo({url:"/plugins/bargain/index/index"})},nav2:function(){t.redirectTo({url:"/plugins/bargain/order-list/order-list"})}}};n.default=f}).call(this,e("543d")["default"])},"2faf":function(t,n,e){"use strict";e.r(n);var o=e("ff4a"),r=e("91a1");for(var i in r)"default"!==i&&function(t){e.d(n,t,function(){return r[t]})}(i);e("f8f2");var u=e("2877"),a=Object(u["a"])(r["default"],o["a"],o["b"],!1,null,"1f9885dd",null);n["default"]=a.exports},"91a1":function(t,n,e){"use strict";e.r(n);var o=e("22e0"),r=e.n(o);for(var i in o)"default"!==i&&function(t){e.d(n,t,function(){return o[t]})}(i);n["default"]=r.a},c1d3:function(t,n,e){},f8f2:function(t,n,e){"use strict";var o=e("c1d3"),r=e.n(o);r.a},ff4a:function(t,n,e){"use strict";var o=function(){var t=this,n=t.$createElement,e=(t._self._c,Number(96));t.$mp.data=Object.assign({},{$root:{m0:e}})},r=[];e.d(n,"a",function(){return o}),e.d(n,"b",function(){return r})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'plugins/bargain/common-buttom-create-component',
    {
        'plugins/bargain/common-buttom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2faf"))
        })
    },
    [['plugins/bargain/common-buttom-create-component']]
]);                
