(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-swiper/swiper"],{1888:function(t,e,n){"use strict";var a=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return a}),n.d(e,"b",function(){return i})},"4ec4":function(t,e,n){"use strict";var a=n("9a20"),i=n.n(a);i.a},8486:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a={name:"bw-swiper",props:{mode:{type:String,default:"scaleToFill"},swiperHeight:{type:Number,default:350},fullScreen:{type:Boolean,default:!1},swiperList:{type:Array,default:function(){return[]}},swiperType:{type:Boolean,default:!1},videoAutoplay:{type:Boolean,default:!1},videoKey:{type:String,default:"src"},imageKey:{type:String,default:"img"},skipHiddenItemLayout:{type:Boolean,default:!1},displayMultipleItems:{type:Number,default:1},nextMargin:{type:String,default:"0px"},previousMargin:{type:String,default:"0px"},vertical:{type:Boolean,default:!1},circular:{type:Boolean,default:!0},duration:{type:Number,default:400},interval:{type:Number,default:2500},current:{type:Number,default:0},autoplay:{type:Boolean,default:!0},indicatorColor:{type:String,default:"#CCCCCC"},indicatorActiveColor:{type:String,default:"#ffffff"},indicatorDots:{type:Boolean,default:!0}},data:function(){return{flag:!0,cardCur:0}},methods:{play:function(){this.flag=!1},pause:function(){this.flag=!0},clickItem:function(t){this.swiperList.length>0&&this.$emit("clickItem",this.swiperList[t])},change:function(t){this.$emit("change",t)},animationfinish:function(t){this.cardCur=t.detail.current,this.$emit("animationfinish",t)}}};e.default=a},"9a20":function(t,e,n){},b6b4:function(t,e,n){"use strict";n.r(e);var a=n("1888"),i=n("fbbc");for(var u in i)"default"!==u&&function(t){n.d(e,t,function(){return i[t]})}(u);n("4ec4");var r=n("2877"),l=Object(r["a"])(i["default"],a["a"],a["b"],!1,null,null,null);e["default"]=l.exports},fbbc:function(t,e,n){"use strict";n.r(e);var a=n("8486"),i=n.n(a);for(var u in a)"default"!==u&&function(t){n.d(e,t,function(){return a[t]})}(u);e["default"]=i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-swiper/swiper-create-component',
    {
        'components/page-component/app-swiper/swiper-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b6b4"))
        })
    },
    [['components/page-component/app-swiper/swiper-create-component']]
]);                
